name: ai1

services:
  portfolio-research:
    image: kvsc999/airesearch:latest
    build: .
    container_name: portfolio-research
    env_file: .env
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

